spring:
  application:
    name: cadastro
  datasource:
    url: jdbc:mysql://localhost:3306/cadastro
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:mysql://localhost:3306/cadastro
    user: admin
    password: admin

logging:
  level:
    org.flywaydb: DEBUG